---
- name: copy web files to nodeserver
  hosts: testservers
  tasks:
    ansible.builtin.copy:
    src: src=https://github.com/daminhogit/kaikki/blob/main/Kaikki/kaikki_admin-web/kaikki_admin-main/public/index.html
    dest: /var/www/html/index.html
