---
- name: Download App Content & Extracting File to nodeserver
  hosts: testservers
  ansible.builtin.unarchive:
    src: https://github.com/raghudevopsb69/{{COMPONENT}}/archive/refs/heads/main.zip
    dest: "/tmp"
    remote_src: yes

- name: Copy Extracted App Content to App location
  hosts: testservers
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: "{{ APP_LOC }}/"
    remote_src: yes
