---
- name: copy web files to nodeserver
  hosts: testservers
  become: true
  become_user: centos
  gather_facts: true
  tasks:
    - name: "copy file"
      copy: src=https://github.com/daminhogit/kaikki/blob/main/Kaikki/kaikki_admin-web/kaikki_admin-main/public/index.html dest=/var/www/html/index.html
