---
- name: Download App Content & Extracting File to nodeserver
  hosts: testservers
  gather_facts: false
  tasks:
    - name: Download and unarchive
      src: https://github.com/raghudevopsb69/{{COMPONENT}}/archive/refs/heads/main.zip
      dest: "/tmp"
      remote_src: yes
    - name: copy file
      src: /tmp/{{COMPONENT}}-main/
      dest: "{{ APP_LOC }}/"
      remote_src: yes




